name: Buyify

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  iconic: ^0.1.0
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  fan_carousel_image_slider: ^0.1.2
  awesome_snackbar_content: ^0.1.3
  loading_indicator: ^3.1.1
  animated_loading_indicators: ^1.0.0+4
  shimmer: ^3.0.0
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: iconsax
      fonts:
        - asset: assets/fonts/iconsax.ttf
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Regular.ttf