import 'package:Buyify/core/helpers/functions.dart';
import 'package:Buyify/core/utils/app_colors.dart';
import 'package:Buyify/core/utils/app_text.dart';
// import 'package:Buyify/features/category_view/view/widget/widgets.dart';
import 'package:Buyify/features/featured_product/view/widgets/widgets.dart';
import 'package:Buyify/features/home/bloc/home_bloc.dart';
import 'package:Buyify/features/home/data/models/home_model.dart';
import 'package:Buyify/features/home/data/repo/home_repo_impl.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:iconic/iconic.dart';
import 'package:lottie/lottie.dart';

part '../../../../core/common/custom_appBar.dart';
part '../../../../core/common/item_box.dart';
part '../../../../core/common/line_separate.dart';
part '../../../../core/common/search_box.dart';
part '../home_view.dart';
part 'banners.dart';
part 'category_section.dart';
part 'dialog_product_action.dart';
part 'image_box.dart';
part 'products_section.dart';
part 'title_sections.dart';
